import test from 'node:test';
import assert from 'node:assert/strict';
import { appendChanges, branchForIssue, createDraftPull, publishChanges } from '../cloud-coder/src/broker.js';

test('publishes one non-force commit from a checked workspace change set', async () => {
  const calls = [];
  const gh = {
    async request(method, path, options = {}) {
      calls.push({ method, path, body: options.body });
      if (path === '/repos/o/r/git/commits/base-sha') return { data: { tree: { sha: 'base-tree' } } };
      if (path === '/repos/o/r/git/blobs') return { data: { sha: `blob-${calls.length}` } };
      if (path === '/repos/o/r/git/trees') return { data: { sha: 'next-tree' } };
      if (path === '/repos/o/r/git/commits') return { data: { sha: 'next-commit' } };
      if (path === '/repos/o/r/git/refs') return { data: { ref: 'refs/heads/shipyard/issue-7' } };
      if (path === '/repos/o/r/git/refs/heads/shipyard%2Fissue-7') return { data: { object: { sha: 'next-commit' } } };
      if (path === '/repos/o/r/pulls') return { data: { number: 12, html_url: 'https://example.test/pr/12' } };
      throw new Error(`Unexpected ${method} ${path}`);
    },
  };

  const branch = branchForIssue(7);
  await publishChanges(gh, {
    owner: 'o',
    repo: 'r',
    baseSha: 'base-sha',
    branch,
    changes: [
      { path: 'src/new.js', content: 'export const value = 1;\n' },
      { path: 'src/old.js', content: null },
    ],
    message: 'Shipyard: implement #7',
  });
  const pull = await createDraftPull(gh, {
    owner: 'o',
    repo: 'r',
    branch,
    base: 'main',
    issue: { number: 7, title: 'Add a guard' },
  });

  assert.equal(branch, 'shipyard/issue-7');
  assert.equal(pull.number, 12);
  assert.deepEqual(calls.at(-1), {
    method: 'POST',
    path: '/repos/o/r/pulls',
    body: {
      title: 'Shipyard: Add a guard',
      head: 'shipyard/issue-7',
      base: 'main',
      draft: true,
      body: 'Implements #7. Generated by Shipyard Cloud Coder; awaiting Cloud Reviewer and human review.',
    },
  });
  const update = calls.find((call) => call.path === '/repos/o/r/git/refs/heads/shipyard%2Fissue-7');
  assert.deepEqual(update, {
    method: 'PATCH',
    path: '/repos/o/r/git/refs/heads/shipyard%2Fissue-7',
    body: { sha: 'next-commit', force: false },
  });
});

test('refuses invalid branch names and unsafe change paths before writing', async () => {
  assert.throws(() => branchForIssue(0), /Issue number/i);
  await assert.rejects(
    () =>
      publishChanges(
        { request: async () => ({ data: {} }) },
        {
          owner: 'o',
          repo: 'r',
          baseSha: 'base',
          branch: 'shipyard/issue-1',
          changes: [{ path: '../x', content: 'x' }],
          message: 'Shipyard: implement #1',
        },
      ),
    /safe repository path/i,
  );
});

test('removes a newly-created branch when Git Data publishing fails', async () => {
  const calls = [];
  const gh = {
    async request(method, path) {
      calls.push({ method, path });
      if (method === 'POST' && path.endsWith('/git/refs')) return { data: {} };
      if (method === 'GET' && path.endsWith('/git/commits/base')) return { data: { tree: { sha: 'tree' } } };
      if (method === 'POST' && path.endsWith('/git/blobs')) throw new Error('GitHub unavailable');
      if (method === 'DELETE' && path.endsWith('/git/refs/heads/shipyard%2Fissue-8')) return { data: {} };
      throw new Error(`Unexpected ${method} ${path}`);
    },
  };

  await assert.rejects(
    () =>
      publishChanges(gh, {
        owner: 'o',
        repo: 'r',
        baseSha: 'base',
        branch: 'shipyard/issue-8',
        changes: [{ path: 'app.js', content: 'export {};' }],
        message: 'Shipyard: implement #8',
      }),
    /unavailable/i,
  );
  assert.deepEqual(calls.at(-1), { method: 'DELETE', path: '/repos/o/r/git/refs/heads/shipyard%2Fissue-8' });
});

test('adds a repair only when the draft branch is still at the reviewed commit', async () => {
  const calls = [];
  const gh = {
    async request(method, path, options = {}) {
      calls.push({ method, path, body: options.body });
      if (path === '/repos/o/r/git/ref/heads/shipyard%2Fissue-7') return { data: { object: { sha: 'reviewed-sha' } } };
      if (path === '/repos/o/r/git/commits/reviewed-sha') return { data: { tree: { sha: 'reviewed-tree' } } };
      if (path === '/repos/o/r/git/blobs') return { data: { sha: 'repair-blob' } };
      if (path === '/repos/o/r/git/trees') return { data: { sha: 'repair-tree' } };
      if (path === '/repos/o/r/git/commits') return { data: { sha: 'repair-commit' } };
      if (path === '/repos/o/r/git/refs/heads/shipyard%2Fissue-7') return { data: {} };
      throw new Error(`Unexpected ${method} ${path}`);
    },
  };

  await appendChanges(gh, {
    owner: 'o',
    repo: 'r',
    branch: 'shipyard/issue-7',
    expectedSha: 'reviewed-sha',
    changes: [{ path: 'src/app.js', content: 'export const repaired = true;\n' }],
    message: 'Shipyard: repair #7 after Cloud Reviewer',
  });
  assert.deepEqual(calls.at(-1), {
    method: 'PATCH',
    path: '/repos/o/r/git/refs/heads/shipyard%2Fissue-7',
    body: { sha: 'repair-commit', force: false },
  });

  await assert.rejects(
    () =>
      appendChanges(gh, {
        owner: 'o',
        repo: 'r',
        branch: 'shipyard/issue-7',
        expectedSha: 'different-sha',
        changes: [{ path: 'src/app.js', content: 'x' }],
        message: 'repair',
      }),
    /branch moved/i,
  );
});
