import { isSafeRepoPath } from '../../src/repo.js';

export function branchForIssue(number) {
  if (!Number.isInteger(number) || number < 1) throw new Error('Cloud Coder requires a positive Issue number.');
  return `shipyard/issue-${number}`;
}

/** Create a branch, commit an already-tested workspace delta, and never force an update. */
export async function publishChanges(gh, { owner, repo, baseSha, branch, changes, message }) {
  if (!branch.startsWith('shipyard/issue-') || !changes.length) {
    throw new Error('Cloud Coder requires a Shipyard branch and at least one workspace change.');
  }
  for (const change of changes) {
    if (!isSafeRepoPath(change.path))
      throw new Error(`Cloud Coder change is not a safe repository path: ${change.path}`);
    if (change.content !== null && typeof change.content !== 'string') {
      throw new Error(`Cloud Coder change content must be text or deletion: ${change.path}`);
    }
  }

  const encodedBranch = encodeURIComponent(branch);
  let branchCreated = false;
  try {
    await gh.request('POST', `/repos/${owner}/${repo}/git/refs`, {
      body: { ref: `refs/heads/${branch}`, sha: baseSha },
    });
    branchCreated = true;
    const commit = await gh.request('GET', `/repos/${owner}/${repo}/git/commits/${encodeURIComponent(baseSha)}`);
    const tree = [];
    for (const change of changes) {
      if (change.content === null) {
        tree.push({ path: change.path, mode: '100644', type: 'blob', sha: null });
        continue;
      }
      const blob = await gh.request('POST', `/repos/${owner}/${repo}/git/blobs`, {
        body: { content: change.content, encoding: 'utf-8' },
      });
      tree.push({ path: change.path, mode: '100644', type: 'blob', sha: blob.data.sha });
    }
    const nextTree = await gh.request('POST', `/repos/${owner}/${repo}/git/trees`, {
      body: { base_tree: commit.data.tree.sha, tree },
    });
    const nextCommit = await gh.request('POST', `/repos/${owner}/${repo}/git/commits`, {
      body: { message, tree: nextTree.data.sha, parents: [baseSha] },
    });
    await gh.request('PATCH', `/repos/${owner}/${repo}/git/refs/heads/${encodedBranch}`, {
      body: { sha: nextCommit.data.sha, force: false },
    });
    return nextCommit.data.sha;
  } catch (error) {
    if (branchCreated) await deleteBranch(gh, { owner, repo, branch }).catch(() => null);
    throw error;
  }
}

export function deleteBranch(gh, { owner, repo, branch }) {
  return gh.request('DELETE', `/repos/${owner}/${repo}/git/refs/heads/${encodeURIComponent(branch)}`);
}

export function createDraftPull(gh, { owner, repo, branch, base, issue }) {
  return gh
    .request('POST', `/repos/${owner}/${repo}/pulls`, {
      body: {
        title: `Shipyard: ${issue.title}`,
        head: branch,
        base,
        draft: true,
        body: `Implements #${issue.number}. Generated by Shipyard Cloud Coder; awaiting Cloud Reviewer and human review.`,
      },
    })
    .then((result) => result.data);
}
